# Generated by Django 4.2.13 on 2024-07-01 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myesportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('rank1', models.CharField(max_length=100, null=True)),
                ('rank2', models.CharField(max_length=100, null=True)),
                ('rank3', models.CharField(max_length=100, null=True)),
                ('rank4', models.CharField(max_length=100, null=True)),
                ('rank5', models.CharField(max_length=100, null=True)),
                ('rank6', models.CharField(max_length=100, null=True)),
                ('rank7', models.CharField(max_length=100, null=True)),
                ('rank8', models.CharField(max_length=100, null=True)),
                ('rank9', models.CharField(max_length=100, null=True)),
                ('number_of_players', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, null=True)),
                ('game', models.CharField(max_length=100, null=True)),
                ('name_lastname', models.CharField(max_length=100, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('male', 'ชาย'), ('female', 'หญิง')], max_length=6, null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('line', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='WorkPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='work_pictures/')),
                ('player_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_pictures', to='myesportapp.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('required_rank_min', models.CharField(blank=True, max_length=100, null=True)),
                ('required_rank_max', models.CharField(blank=True, max_length=100, null=True)),
                ('members_needed', models.IntegerField(null=True)),
                ('additional_details', models.TextField(null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myesportapp.game')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='myesportapp.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
