# Generated by Django 4.2.13 on 2024-05-21 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myesportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, null=True)),
                ('game', models.CharField(max_length=100, null=True)),
                ('name_lastname', models.CharField(max_length=100, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('male', 'ชาย'), ('female', 'หญิง')], max_length=6, null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('line', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_pictures/')),
                ('player_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_pictures', to='myesportapp.playerprofile')),
            ],
        ),
    ]
