# Generated by Django 4.2.13 on 2024-05-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myesportapp', '0002_playerprofile_workpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members_needed', models.IntegerField()),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myesportapp.game')),
                ('required_rank_max', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_max_ranks', to='myesportapp.rank')),
                ('required_rank_min', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_min_ranks', to='myesportapp.rank')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='ranks',
            field=models.ManyToManyField(related_name='games', to='myesportapp.rank'),
        ),
    ]
