# Generated by Django 4.2.13 on 2024-07-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myesportapp', '0002_game_playerprofile_alter_userprofile_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='status_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='status_pending',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
