# Generated by Django 4.2.13 on 2024-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myesportapp', '0004_alter_joinrequest_status_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='status_approved',
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='status_pending',
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
    ]
