# Generated by Django 4.2.13 on 2024-05-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myesportapp', '0007_joinrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinRequest',
        ),
    ]
