# Generated by Django 4.2.13 on 2024-07-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myesportapp', '0007_alter_teammember_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='number_of_players',
        ),
    ]
