# Generated by Django 4.2.13 on 2024-07-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myesportapp', '0008_remove_game_number_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
