# Generated by Django 4.2.13 on 2024-07-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myesportapp', '0009_game_number_of_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='number_of_players',
        ),
    ]
