# Generated by Django 4.2.13 on 2024-08-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myesportapp', '0011_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myesportapp.playerprofile'),
        ),
    ]
